version: '3'

services:
  sentiment_analysis_web:
    container_name: sentiment_analysis_web
    build:
      context: .
      dockerfile: DockerFile
    command: ./deployment/start-app
    restart: always
    ports:
      - "127.0.0.1:18000:8001"
