#!/bin/bash

# Collect static files not required. Serving content from CDN
#echo "Collect static files"
python manage.py collectstatic --noinput

# Apply database migrations
echo "Apply database migrations"
python manage.py migrate --noinput

#Remove unused permissions and contenttypes
python manage.py remove_stale_contenttypes --include-stale-apps --no-input

# Start server
echo "Starting server"

#python manage.py runserver 0.0.0.0:8000
hypercorn core.wsgi:application --bind 0.0.0.0:8001
